name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Or your main branch name (e.g., master)
  workflow_dispatch: # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js (Optional)
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Or another suitable version

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'  # Upload everything from the root directory

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4